#ifndef ZUI_CURSOR_H
#define ZUI_CURSOR_H

typedef enum ZuiCursor {
  ZUI_CURSOR_DEFAULT,
  ZUI_CURSOR_POINTER,
  ZUI_CURSOR_TEXT,
  ZUI_CURSOR_CROSSHAIR,
  ZUI_CURSOR_MOVE,
  ZUI_CURSOR_RESIZE_N,
  ZUI_CURSOR_RESIZE_S,
  ZUI_CURSOR_RESIZE_E,
  ZUI_CURSOR_RESIZE_W,
  ZUI_CURSOR_RESIZE_NE,
  ZUI_CURSOR_RESIZE_NW,
  ZUI_CURSOR_RESIZE_SE,
  ZUI_CURSOR_RESIZE_SW,
  ZUI_CURSOR_NOT_ALLOWED,
  ZUI_CURSOR_GRAB,
  ZUI_CURSOR_GRABBING,
  ZUI_CURSOR_COL_RESIZE,
  ZUI_CURSOR_ROW_RESIZE,
  ZUI_CURSOR_COUNT
} ZuiCursor;

#endif
